[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3cb20d84832bd3893c9a5ae4b880ddb2cfbba7a1"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "c8c1e0bd9884365df12781d404e75fc39e6a0d27db81eeca939cd01adcfa75dc"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.aarch64-linux-musl-cxx03.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18b7c9cb769c0c95377bc6cd7aeea6a1a26d8560"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "9df80f133c16bad187dc6737a4239b97fcdb8c0b4233c4e02ed747bdbcebae18"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.aarch64-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "980601b73b9a8e481f52d1a1b2bca3cfd9095e72"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "e3182ae5b416a16f580c6afbd843618a893601dd51412165ed47156def6e59e3"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee64802cf4eef7df844cf2f37b29a3ea24db6edb"
os = "windows"

    [[Cbc.download]]
    sha256 = "4a5f956d2647779b4a1db5ddf0a147c9c9a0a8bf0ffaca77892bb2a0d4b6ffa3"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb01cfeb96c4ff137947567c71f3ff77e35adb7f"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "4a118e6b4f2c79d07a8bfe9ac77dc84f931353e3ea9b17456e60be043b8b4b20"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.i686-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e52af4ae9d05945ba374e5050fe0987b75bf1964"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "80d53171b25d31ad9a80053760330759ca70d84b4ea090bfa419664a5db97158"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.x86_64-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "998a658b2391965633a1b1e8d547cb2d2468c656"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "21229694dbf7cc862d39575fedc844f88c588e4e5e2b26708fb38dd4f905531f"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11b480dcf2e9c695486f96f3790478e6631a0d3f"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "31a8d19240e8ebad4060798805b5b0d17287c387341af5cc77c3d4d695f263a9"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.i686-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e9da18d77c12baa80907fb0c94816bad829347a"
os = "macos"

    [[Cbc.download]]
    sha256 = "22f3c05dcf7e820ae0bbb28f49c887361f4e9f6d2e730990a297b73d8b1143ff"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "984e4977cf83781677870eecf1a203c7a723d3c5"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "e1cd22e1b870cf81a46499703a69c4c395a0548f4c32cf58a7a9f9ae28771497"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.i686-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "962cfa549b786f9ed6e833a186fbe3339f75c89c"
os = "windows"

    [[Cbc.download]]
    sha256 = "98652a43b98e4d280a8ba0d15e05a4cfd1bc207e156c3746aaca78274d72b4bd"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ac5af5923da476cf695815b809e3054866b9679"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "c084045ffe533f8892e5996b215c16ae0f707333435a72167c46e1420eb00e3e"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61d50f61718adb174248e2002e66ae172566d993"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "137abdaf33f8ac45a99484202d53eea9e441ff531a28687f9d0d4bb74f289fcd"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1950b61f926f648bf830f07193293afde49d04b7"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "73024326ee1986f97d70d59dd3e1f918d70537fad75536cd714f8d32f316c75c"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.x86_64-linux-musl-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de2d361b996c74cd2be712e44abe8831f531ddf1"
os = "macos"

    [[Cbc.download]]
    sha256 = "b00ca1cf4b8a06706258f9e333e9b1a1e0f1c78bc235b40aaefae70803a30dad"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42d2b03baf9258461640dd085460839306ecf517"
os = "windows"

    [[Cbc.download]]
    sha256 = "076738dd23c32134eae85b3fcd48c12a4d5d3b7c0250ee0d704acce2b15ea2be"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.i686-w64-mingw32-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "346064c5849cb3de2fc12ead0e19eb20960d184e"
os = "windows"

    [[Cbc.download]]
    sha256 = "a4ec2ea436b87d81f7d417d2407012eabfc17ba59f7e0c1d68d70f29fd522946"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.i686-w64-mingw32-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65ff619abe25d1e34e125972c0d144e90363e606"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "90832f7cf43127be63017ba8a3dbbd0402f4108ca103fd9766fd2d797fbac307"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3de44e8fd9b3d6b45ee59f7fd4d669e194d17e2"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "62d48cb934be436d7a23aa9a935fbe2928a1ae1b25fa42741e90efcee5d2b4e7"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5196a03c332aea0b05486195774606bfb188e663"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "d1ca205f3e54941577bbf7093ef49d85369e9cccc8282195c21341a6612bcb5e"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a6f2220c021fc50d44f6e91225bb45e8104fc23"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "9bda36f902fbdce3c5a345f667a0ef81b539e89dcecb0e5683adfd9624f29023"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07a3ce8daac37b1221041dd5a9fe49172a88451e"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "e67cd2c70107cd3a1e0c93abfa3debe320b5a35acb8102536122d2d3b065d052"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+2/Cbc.v2.10.3.i686-linux-musl-cxx03.tar.gz"
