[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fb2715a037ea04f789f65a65d2bd2c8ce2a2071"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "8eb0d143fb7a5862048fa468aa3ba1eeafee868c5ca261de49ccf103752cdeea"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.aarch64-linux-musl-cxx03.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74e42de266c883228c2ab54b4ae7945d2d2f6575"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "e205d92dbffb258a55ebae238aa47631c536001fb6ef45e73c444df843667fc3"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.aarch64-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79d924c07af8bb634378db149faed56e0c321f8c"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "93f46bad33653587937a66e9c6dda934deafeb91d592bd1d00ee1ac2ad2f5c07"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b52d7b4fc2e4b96739deca14ee9111e32b37ca6f"
os = "windows"

    [[Cbc.download]]
    sha256 = "8f45ff317fa30e03e2ee360f8379a6824e22c804bc86c34f9088f4aecf0320cd"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c40a4bd7d4611ac13a4a9009a46029e29bb763b0"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "4c0abf951616439660aea50975fb80636151bfeba97ae28a421b4bb0df9c1817"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.i686-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdff9ac34a58408c94c1e2fc2e6dbb45e4275fab"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "70d7c077ecfc4b0e84d4810176a2f70b140ea769a5f25c733ce6d41e7f635339"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.x86_64-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "056b4cb3528e5e434b487d9d59d5472541008f4a"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "bf0959277a5abf3dd028950f53325f1d1f0c52b4ea9ae9ed702f1de4b4132321"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bccb71a51e6d3cc7f1515937b427cc447e202f2f"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "aa5d672df40f52ececd27880b898881965ad92b81e63ecb6f5bbe54fd8e73699"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.i686-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36fd286ace66ad1d1eee7705f04ebe6a2dededa5"
os = "macos"

    [[Cbc.download]]
    sha256 = "d748fbbae7eed4fe912f0d06edfcb4fd64a0d82d92616eb2114b619884f676b2"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4729550870fa81d62ecebdc2945efe0ce362ac8c"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "32edc6cec67acb26bb9dda18b5591297f01203e449932dcccf88da9fdc1a6f23"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.i686-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6772f56490fc85e77023447a964786c464db98ae"
os = "windows"

    [[Cbc.download]]
    sha256 = "81627c12a815ea67ae26f5ef2d87e9b4dc6281ca24c6db36fa71cc9401974dca"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3875b74e054aa8f3ece624e08efc76efd4621a97"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "9364413ea91c191dd74dacf534ebd2497724ba289c27edda1598c71015734f11"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6020a41f7ea3674741c9337efacb96dff87f400e"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "7b2c775995b98d91cb5503a4ecba732287f8164d7353a1bd06d81f59084f0c89"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85d4fd54c0228d6e3922e83971f484bbc3e99aab"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "75c11bd0ab711f1409cfac79f0ef125782a02bc1731f36556cae0af66e3bf03b"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.x86_64-linux-musl-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c92c4a31154ddffde2153aea6ca25718ab7463fe"
os = "macos"

    [[Cbc.download]]
    sha256 = "879b94778ef94ece12f6aa986a259498be0fd30c86df3278197ff8e55194998d"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8485cae89ebc083467c632f5c1579ff0949b7721"
os = "windows"

    [[Cbc.download]]
    sha256 = "50be3819a14ee2c81fa5dc57889bdd83312af1f935bb273ae333a7393a33ea87"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.i686-w64-mingw32-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "952b96640d7ffb90b8ce5e3d3cf585f0f4742e41"
os = "windows"

    [[Cbc.download]]
    sha256 = "88ccf96649d7de0705b2c9f6d88e06621ae7381b2a4a48c254d297d5713ce4e5"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.i686-w64-mingw32-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8777a5f2f1cf8f26cd4e45ea377db83485629f36"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "f25b97443e4525a2ff9f602318981839e3f2adc263a8c6b27408fbc77a326fb5"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "986b2113f74e68a543dd96b5cccf96911983a503"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "d6c94ab889402dd5fb32b01d3f15df41de4f2cd88a957dad0342d6632ab67f82"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8da3d1fd12ea88a8ce544b8b8ba7273024f61224"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "18870e66851578a4315dc9548112931c57858a0f9e4be3b046debe869688180e"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f0bd3fc502f083f8b1a0957bca1659deb0a72da"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "1f94e8e4c84d1b2660548dfcf3f136b554c4f3e6dc84e7da336a6a653b53c679"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cf81bf10b9c40bc5e06a6eaec00387b00f6f9d5a"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "563de91e51720bd7b1f7dd25ecdefbe973be78920471f49df3b65db8eb085f32"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+1/Cbc.v2.10.3.i686-linux-musl-cxx03.tar.gz"
