[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "235cb3a3db26c35de1bcce915b8400c1cf56e879"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "0f81f79439b6c26564697777109db7cd9498083dba8b97c595402712cc9f8c40"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.aarch64-linux-musl-cxx03.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a18ebdbc52704f250d19dc042b4273df4b977505"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "5e0e7d845c797ebd68328f6269e69d3e8e1d37691a55d1e222ca64b70243fbb9"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.aarch64-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e54c2e0c6f00a45db842840d7ff1829613f49dec"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "bb392f9454e3b8e44be440ab04edce86fc944cf35039fe99b8e352d0cc9224e8"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec8d7d8c10b21416aabaa2c21b9334fd2d61cf6f"
os = "windows"

    [[Cbc.download]]
    sha256 = "fc06ad31d64d845347a107bae0e4f2b8b5b5d39af66bf9943e25fb05db799f51"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17f63cf61925f1938bb06f3177178bbd520939d4"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "4b641e66b342576634dcc9838699100600fdd8954493f8fa47f065f67a75f916"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.i686-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4494752a8167449d8de3c9108302f0f02da8a216"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "c005c3938f840bf314d02fad23db00f12d798d5f5597b5c2b522cf9fdd9aff4f"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.x86_64-linux-musl-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "feb844eabdd7e286f21d397b503443a1d9cb6685"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "616a711bc70d6e985199fec06498a0594c2f90f89b7163d03bfd1c95f7a68910"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c1f2f0a19677a7f00708903d27ac46da6bdc909"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "1ad57ca0c9376fa0b7104f1536aaf22be7e8008b5eca4815b7e20a9ddeafe93f"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.i686-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb31209bdb0e3f72ec592bc1aa4ef1042b47a1b2"
os = "macos"

    [[Cbc.download]]
    sha256 = "48f50090d10b5430ba43d313da137032134070e513067897483f9e8366d6c564"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a02a43506ce9d2f337896b059a4abf75dc8db332"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "b50de1a5a8cf315e0d56e6386bdc62a08d44bff1d1cce40fb895f753db970057"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.i686-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "920d5f85f23d3c9591e43d37277aa8b5543835b9"
os = "windows"

    [[Cbc.download]]
    sha256 = "118d199c96e32c2ccfc4ea87fe7f317c08364db1cbcb3584f88c61d6f4dcf54e"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5214fe46db5ad248f7d06b953d4c3a4ad065961"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "cabad79fa76ce6716b7411d26a3718368b1109db3142f6415a7d3df388c09561"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de2d9ce7cf3697375e532920e23a2006a9be7dc6"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "2cf3d477c3f12fc4a167e7ddc16d20d225122834f6da78247c5ba58244fb8875"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c13e512fc0df662ef333d7218906fee3acb467f6"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "8264d2a1bf5c013c03ffa6c4bfa18af95a27c8afa9fd0593a4c6cd2d947a4826"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.x86_64-linux-musl-cxx03.tar.gz"
[[Cbc]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d36bc52a0d9a99ae365e0b9ec6c2f97d92db4f29"
os = "macos"

    [[Cbc.download]]
    sha256 = "679ea1803469559561430c4410c0f0ea6caeedd3f17346fec80c4ffeb08ea6e8"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15860e369811183ae806e34cc8ef4da87e9ce572"
os = "windows"

    [[Cbc.download]]
    sha256 = "447f52a2b1a431d2081fa47d43623c0f0ef21753d61acf0bfde7aa916fbe9b7b"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.i686-w64-mingw32-cxx03.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bc38d61fb79c17d057f001e06ba2077dbb2b11e"
os = "windows"

    [[Cbc.download]]
    sha256 = "bbe2b41cdee9b746f1407c36becbbeec6e75f9bc897a4dafa3c4e4d60a576199"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.i686-w64-mingw32-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7a08b9583a957a9c4ec10971704c5edf05c36ca"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "3ba8bc9d38704feaa8b908e633e317159cfad6d113d948bca6266d346707acb1"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "09d224921d2562bba9f99ef302879dff092e4b44"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "34a85fdd2c84c36a895e5a1bdf801215a636f871b7751155519ee31dceb3c769"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Cbc]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c0006a73b6cae26716c5bc70b647520e1709710"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "53a58b7aa7da734f8770cb51eb5fab801ea2e854d3b7fa41e01371ae2f2d9786"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Cbc]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1303dacd79e4d33798f16f1a4a475ef8a3a4aa12"
libc = "glibc"
os = "linux"

    [[Cbc.download]]
    sha256 = "e181f20ac801751c2b7e42c25739588ae050bedb4be24a5dba14d7516ced265d"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Cbc]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32c9da10a0f3b4ba91d3fdfbe1cf504d59914349"
libc = "musl"
os = "linux"

    [[Cbc.download]]
    sha256 = "863195abe3e0c795e3e20cd3e825e3fb6e1ddf24865d97e7fca5795c453878f8"
    url = "https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/download/Cbc-v2.10.3+0/Cbc.v2.10.3.i686-linux-musl-cxx03.tar.gz"
